# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2a8e5ba105d16fa406a1b0dfabeab9e31f7fbd65c0592d3ad70c15eddff46d9e8bb33ecc852a4830a8ff01b54ed8c98d560605662e17b4a18f0a5b544cc14867

test:
  secret_key_base: 016f08505a24f51268b81a98c250b1ec6377d800bbb856ec027de7182c0136fc93407ca9413ccaeed2839a5018f8ebc88df73b7f47f2ed6b7a3442657a65f596

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
